const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sample={name:"RomitJSON",version:"1.0",tools:["format","validate","convert"],free:true};
const input=$("#jsonInput"),input2=$("#jsonInput2"),output=$("#jsonOutput"),message=$("#toolMessage"),select=$("#toolSelect"),compareWrap=$("#compareInputWrap"),fileInput=$("#fileInput"),drop=$("#dropzone");
function setMessage(t,error=false){message.textContent=t;message.style.color=error?"#d85b5b":"var(--accent-dark)"}
function parseText(text){try{return{value:JSON.parse(text)}}catch(e){return{error:e}}}
function pretty(v){return JSON.stringify(v,null,2)}
function flattenRows(v){if(!Array.isArray(v))throw new Error("JSON to CSV needs a JSON array.");if(!v.length)return{headers:[],rows:[]};if(!v.every(x=>x&&typeof x==="object"&&!Array.isArray(x)))throw new Error("JSON to CSV expects an array of objects.");const headers=[...new Set(v.flatMap(x=>Object.keys(x)))];return{headers,rows:v.map(x=>headers.map(h=>{const z=x[h];return z===undefined||z===null?"":typeof z==="object"?JSON.stringify(z):String(z)}))}}
function csvEscape(v){let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return/[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(v){const{headers,rows}=flattenRows(v);return[headers,...rows].map(r=>r.map(csvEscape).join(",")).join("\r\n")}
function yamlScalar(v){if(v===null)return"null";if(typeof v==="string"){if(v===""||/[:#\[\]{},&*!|>'"@]/.test(v)||/^(true|false|null|~)$/i.test(v)||/^[\-?]\s/.test(v))return JSON.stringify(v);return v}return String(v)}
function toYaml(v,indent=0){const pad=" ".repeat(indent);if(v===null||typeof v!=="object")return yamlScalar(v);if(Array.isArray(v)){if(!v.length)return"[]";return v.map(x=>x&&typeof x==="object"?pad+"-\n"+toYaml(x,indent+2):pad+"- "+toYaml(x,indent+2)).join("\n")}const keys=Object.keys(v);if(!keys.length)return"{}";return keys.map(k=>{const key=/^[A-Za-z_][A-Za-z0-9_-]*$/.test(k)?k:JSON.stringify(k),x=v[k];return x&&typeof x==="object"?pad+key+":\n"+toYaml(x,indent+2):pad+key+": "+toYaml(x,indent+2)}).join("\n")}
function xmlName(k){return String(k).replace(/[^A-Za-z0-9_.-]/g,"_").replace(/^[^A-Za-z_]+/,"_")||"item"}
function xmlEsc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}
function toXml(v,name="root",level=0){const p="  ".repeat(level),tag=xmlName(name);if(v===null||typeof v!=="object")return p+"<"+tag+">"+xmlEsc(v===null?"":v)+"</"+tag+">";if(Array.isArray(v))return v.length?v.map(x=>toXml(x,"item",level)).join("\n"):p+"<"+tag+"/>";const inner=Object.entries(v).map(([k,x])=>toXml(x,k,level+1)).join("\n");return inner?p+"<"+tag+">\n"+inner+"\n"+p+"</"+tag+">":p+"<"+tag+"/>"}
function typeName(v){if(v===null)return"any";if(Array.isArray(v)){if(!v.length)return"unknown[]";const types=[...new Set(v.map(typeName))];return types.length===1?types[0]+"[]":"Array<"+types.join(" | ")+">"}if(typeof v==="number")return"number";if(typeof v==="boolean")return"boolean";if(typeof v==="string")return"string";if(typeof v==="object")return"object";return"any"}
function pascal(s){return String(s).replace(/[^A-Za-z0-9]+(.)?/g,(_,c)=>c?c.toUpperCase():"").replace(/^./,c=>c.toUpperCase())||"Root"}
function inferInterfaces(v,name="Root",seen=new Set()){const defs=[];if(Array.isArray(v)){v.forEach(x=>{if(x&&typeof x==="object")defs.push(...inferInterfaces(x,name,seen))});return defs}if(!v||typeof v!=="object"||seen.has(name))return defs;seen.add(name);const lines=Object.entries(v).map(([k,x])=>{if(x&&typeof x==="object"&&!Array.isArray(x)){const n=pascal(k);defs.push(...inferInterfaces(x,n,seen));return"  "+JSON.stringify(k)+": "+n+";"}return"  "+JSON.stringify(k)+": "+typeName(x)+(x===null?" | null":"")+";"});defs.push("interface "+name+" {\n"+lines.join("\n")+"\n}");return defs}
function deepDiff(a,b,path="$",out=[]){if(Object.is(a,b))return out;if(typeof a!==typeof b||a===null||b===null){out.push(path+": "+pretty(a)+" → "+pretty(b));return out}if(Array.isArray(a)||Array.isArray(b)){if(!Array.isArray(a)||!Array.isArray(b))out.push(path+": type differs");else{if(a.length!==b.length)out.push(path+": array length "+a.length+" → "+b.length);for(let i=0;i<Math.max(a.length,b.length);i++){if(i>=a.length)out.push(path+"["+i+"]: added "+pretty(b[i]));else if(i>=b.length)out.push(path+"["+i+"]: removed "+pretty(a[i]));else deepDiff(a[i],b[i],path+"["+i+"]",out)}}return out}if(typeof a==="object"){const keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys){if(!(k in a))out.push(path+"."+k+": added "+pretty(b[k]));else if(!(k in b))out.push(path+"."+k+": removed "+pretty(a[k]));else deepDiff(a[k],b[k],path+"."+k,out)}return out}out.push(path+": "+String(a)+" → "+String(b));return out}
function renderTree(v){const walk=(x,key="$",depth=0)=>{const pad="  ".repeat(depth);if(x&&typeof x==="object"){const entries=Array.isArray(x)?x.map((z,i)=>[i,z]):Object.entries(x);let s=pad+key+" "+(Array.isArray(x)?"[":"{")+"\n";for(const[k,z]of entries)s+=walk(z,String(k),depth+1);return s+pad+(Array.isArray(x)?"]":"}")+"\n"}return pad+key+": "+JSON.stringify(x)+"\n"};output.textContent=walk(v)}
function run(){const tool=select.value,text=input.value.trim(),r=parseText(text);if(r.error&&tool!=="editor"){output.textContent="";setMessage("Invalid JSON: "+r.error.message,true);return}try{let result="",name="";if(tool==="formatter"||tool==="editor"){result=pretty(r.value);name=tool==="editor"?"Edited JSON":"Formatted JSON";input.value=result}else if(tool==="validator"){result="✓ Valid JSON — syntax is correct.";name="Validation result"}else if(tool==="minifier"){result=JSON.stringify(r.value);name="Minified JSON"}else if(tool==="viewer"){renderTree(r.value);result=output.textContent;name="JSON Tree"}else if(tool==="jsoncsv"){result=toCsv(r.value);name="CSV result"}else if(tool==="jsonyaml"){result=toYaml(r.value);name="YAML result"}else if(tool==="jsonxml"){result='<?xml version="1.0" encoding="UTF-8"?>\n'+toXml(r.value);name="XML result"}else if(tool==="typescript"){const defs=inferInterfaces(r.value);result=defs.reverse().join("\n\n");name="TypeScript result"}else if(tool==="compare"){const r2=parseText(input2.value.trim());if(r2.error)throw new Error("Second JSON is invalid: "+r2.error.message);const d=deepDiff(r.value,r2.value);result=d.length?d.map(x=>"• "+x).join("\n"):"✓ The two JSON documents are identical.";name="Compare result"}output.textContent=result;$("#resultTitle").textContent=name.toUpperCase();setMessage(tool==="validator"?"JSON is valid.":"Done. Result is ready to copy or download.")}catch(e){output.textContent="";setMessage(e.message,true)}}
function updateMode(){compareWrap.classList.toggle("show",select.value==="compare")}
$$("[data-tool]").forEach(a=>a.addEventListener("click",e=>{const t=a.dataset.tool;if(t){e.preventDefault();select.value=t;updateMode();$("#workspace").scrollIntoView({behavior:"smooth"});setTimeout(run,160)}}));select.addEventListener("change",updateMode);$("#runTool").onclick=run;
$("#sampleBtn").onclick=()=>{input.value=pretty(sample);setMessage("Sample JSON loaded.")};$("#clearBtn").onclick=()=>{input.value="";input2.value="";output.textContent="";setMessage("Workspace cleared.")};
$("#copyBtn").onclick=async()=>{const t=output.textContent;if(!t)return setMessage("Nothing to copy.",true);try{await navigator.clipboard.writeText(t);$("#copyBtn").textContent="Copied!";setTimeout(()=>$("#copyBtn").textContent="Copy",1000)}catch(e){setMessage("Copy failed. Select the result manually.",true)}};
function download(name,text,type){const blob=new Blob([text],{type:type||"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$("#downloadBtn").onclick=()=>{const t=output.textContent;if(!t)return setMessage("Run a tool first.",true);const map={jsoncsv:["result.csv","text/csv"],jsonyaml:["result.yaml","text/yaml"],jsonxml:["result.xml","application/xml"],typescript:["types.ts","text/plain"],compare:["comparison.txt","text/plain"],validator:["validation.txt","text/plain"],minifier:["minified.json","application/json"],formatter:["formatted.json","application/json"],viewer:["view.txt","text/plain"],editor:["edited.json","application/json"]};const[n,m]=map[select.value]||["result.txt","text/plain"];download(n,t,m)};
function loadFile(f){if(f.size>10485760){setMessage("File exceeds the 10MB limit.",true);return}if(!/\.json$/i.test(f.name)&&f.type!=="application/json"){setMessage("Please choose a JSON file.",true);return}const r=new FileReader;r.onload=()=>{input.value=r.result;$("#fileStatus").textContent=f.name+" loaded successfully.";setMessage("File loaded. Choose a tool and run it.");$("#workspace").scrollIntoView({behavior:"smooth"})};r.onerror=()=>setMessage("Could not read this file.",true);r.readAsText(f)}
$("#browseBtn").onclick=e=>{e.stopPropagation();fileInput.click()};$("#ctaBtn").onclick=()=>fileInput.click();drop.addEventListener("click",e=>{if(!e.target.closest("button"))fileInput.click()});fileInput.onchange=()=>fileInput.files[0]&&loadFile(fileInput.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add("drag")};drop.ondragleave=()=>drop.classList.remove("drag");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("drag");const f=e.dataTransfer.files[0];if(f)loadFile(f)};
const modal=$("#pasteModal");$("#pasteBtn").onclick=e=>{e.stopPropagation();modal.classList.add("open");modal.setAttribute("aria-hidden","false");$("#pasteArea").focus()};$("#closeModal").onclick=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true")};$("#usePaste").onclick=()=>{input.value=$("#pasteArea").value;modal.classList.remove("open");modal.setAttribute("aria-hidden","true");$("#workspace").scrollIntoView({behavior:"smooth"});setMessage("JSON pasted. Ready to process.")};modal.addEventListener("click",e=>{if(e.target===modal)$("#closeModal").click()});
$$(".nav-drop-btn").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();const box=btn.parentElement;$$(".nav-dropdown").forEach(x=>x!==box&&x.classList.remove("open"));box.classList.toggle("open");btn.setAttribute("aria-expanded",box.classList.contains("open"))}));document.addEventListener("click",()=>$$(".nav-dropdown").forEach(x=>x.classList.remove("open")));$("#menuBtn").onclick=()=>$("#mainNav").classList.toggle("open");
const theme=localStorage.getItem("romitjson.theme")||"light";document.body.classList.toggle("dark",theme==="dark");document.body.classList.toggle("light",theme==="light");$("#themeBtn").onclick=()=>{const dark=!document.body.classList.contains("dark");document.body.classList.toggle("dark",dark);document.body.classList.toggle("light",!dark);localStorage.setItem("romitjson.theme",dark?"dark":"light")};$("#year").textContent=new Date().getFullYear();updateMode();